# Generated by Django 6.0.2 on 2026-04-27 12:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_billattachment'),
        ('core', '0004_chartofaccount_is_active_alter_accountmapping_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(help_text="Internal label, e.g. 'Monthly rent — Office'.", max_length=120)),
                ('vendor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank to run indefinitely.', null=True)),
                ('next_run_date', models.DateField()),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('due_days', models.PositiveIntegerField(default=30, help_text='Days from bill date to set as due date on each generated bill.')),
                ('auto_approve', models.BooleanField(default=False, help_text='If true, generated bills are posted to books immediately.')),
                ('bill_no_pattern', models.CharField(blank=True, help_text='Optional pattern for generated bill numbers. Tokens: {YYYY-MM}, {YYYY}, {MM}, {DD}, {MON}, {SEQ}.', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-status', 'next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bill_items', to='core.chartofaccount')),
                ('recurring_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.recurringbill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringbill',
            index=models.Index(fields=['status', 'next_run_date'], name='bills_recur_status_6f993b_idx'),
        ),
    ]
