# Generated by Django 6.0.2 on 2026-05-06 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_recurringbill_recurringbillitem_and_more'),
        ('journals', '0004_journalentry_reversal_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_id__isnull', False), models.Q(('bill_no', ''), _negated=True)), fields=('vendor_id', 'bill_no'), name='bills_unique_vendor_invoice_no'),
        ),
    ]
