# Generated by Django 6.0.2 on 2026-05-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_bills_unique_vendor_invoice_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'No approval needed'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
