# Generated by Django 6.0.2 on 2026-03-03 04:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR1Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('location_id', models.PositiveIntegerField()),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('invoice_type', models.CharField(choices=[('B2B', 'B2B Invoice'), ('B2C_LARGE', 'B2C Large (>2.5L)'), ('B2C_SMALL', 'B2C Small'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], max_length=20)),
                ('place_of_supply', models.CharField(blank=True, max_length=2)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cess', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('source_type', models.CharField(choices=[('pos', 'POS Sale'), ('b2b', 'B2B Sale'), ('return', 'Sales Return')], max_length=10)),
                ('source_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['period', 'location_id'], name='gst_returns_period_272b17_idx')],
                'unique_together': {('source_type', 'source_id', 'period')},
            },
        ),
        migrations.CreateModel(
            name='GSTR3BSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('location_id', models.PositiveIntegerField()),
                ('outward_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outward_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outward_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outward_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outward_zero_rated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('itc_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('itc_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('itc_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_payable_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_payable_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_payable_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed')], default='draft', max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('period', 'location_id')},
            },
        ),
    ]
