# Generated by Django 6.0.2 on 2026-03-19 12:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_returns', '0001_initial'),
        ('journals', '0002_alter_journalentry_reference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR1HSNSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('location_id', models.PositiveIntegerField()),
                ('hsn_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uqc', models.CharField(default='NOS', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hsn_code'],
            },
        ),
        migrations.CreateModel(
            name='GSTR2BEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('location_id', models.PositiveIntegerField()),
                ('supplier_gstin', models.CharField(max_length=15)),
                ('supplier_name', models.CharField(max_length=255)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('place_of_supply', models.CharField(blank=True, max_length=2)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('itc_eligible', models.BooleanField(default=True)),
                ('source_po_id', models.PositiveIntegerField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('missing', 'Missing in Books'), ('mismatch', 'Amount Mismatch')], default='unmatched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='ITCReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('location_id', models.PositiveIntegerField()),
                ('supplier_gstin', models.CharField(max_length=15)),
                ('books_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('books_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('books_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('books_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gstr2b_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gstr2b_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gstr2b_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gstr2b_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('partial', 'Partial Match')], default='unmatched', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period', 'supplier_gstin'],
            },
        ),
        migrations.CreateModel(
            name='RCMEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('location_id', models.PositiveIntegerField()),
                ('supplier_gstin', models.CharField(blank=True, max_length=15)),
                ('supplier_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('sac_code', models.CharField(blank=True, max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gstr1entry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='ack_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='ack_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='e_invoice_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='irn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='irn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='is_time_barred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='original_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='original_invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gstr1entry',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gstr1entry',
            name='invoice_type',
            field=models.CharField(choices=[('B2B', 'B2B Invoice'), ('B2C_LARGE', 'B2C Large (>2.5L)'), ('B2C_SMALL', 'B2C Small'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('CDNR', 'Credit/Debit Note (Registered)'), ('CDNUR', 'Credit/Debit Note (Unregistered)'), ('NIL', 'Nil Rated/Exempt')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='gstr1entry',
            index=models.Index(fields=['is_active', 'period'], name='gst_returns_is_acti_81ddcb_idx'),
        ),
        migrations.AddIndex(
            model_name='gstr1hsnsummary',
            index=models.Index(fields=['period', 'location_id', 'is_active'], name='gst_returns_period_6c61e0_idx'),
        ),
        migrations.AddIndex(
            model_name='gstr2bentry',
            index=models.Index(fields=['period', 'location_id'], name='gst_returns_period_067825_idx'),
        ),
        migrations.AddIndex(
            model_name='gstr2bentry',
            index=models.Index(fields=['match_status'], name='gst_returns_match_s_76c08a_idx'),
        ),
        migrations.AddIndex(
            model_name='itcreconciliation',
            index=models.Index(fields=['period', 'location_id'], name='gst_returns_period_d66c1e_idx'),
        ),
        migrations.AddField(
            model_name='rcmentry',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rcm_entries', to='journals.journalentry'),
        ),
        migrations.AddIndex(
            model_name='rcmentry',
            index=models.Index(fields=['period', 'location_id'], name='gst_returns_period_6959de_idx'),
        ),
    ]
