# Generated by Django 6.0.2 on 2026-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_returns', '0002_gstr1hsnsummary_gstr2bentry_itcreconciliation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway_bill_no', models.CharField(blank=True, help_text='12-digit e-Way Bill number assigned by NIC portal.', max_length=20)),
                ('generated_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='1 day per 200 km (CGST Rule 138(10)).', null=True)),
                ('reference_type', models.CharField(help_text='B2BSalesOrder, PurchaseOrder, SalesReturn, StockTransfer, Manual', max_length=30)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('supply_type', models.CharField(choices=[('Outward', 'Outward (Sale / Supply)'), ('Inward', 'Inward (Purchase / Return)')], default='Outward', max_length=10)),
                ('sub_type', models.CharField(choices=[('Supply', 'Supply'), ('Export', 'Export'), ('Import', 'Import'), ('JobWork', 'Job Work'), ('ForOwnUse', 'For Own Use'), ('SalesReturn', 'Sales Return'), ('Exhibition', 'Exhibition or Fairs'), ('Lineksales', 'Line Sales'), ('Recipientnotknown', 'Recipient Not Known'), ('Others', 'Others'), ('SKD/CKD', 'SKD/CKD/Lots')], default='Supply', max_length=20)),
                ('doc_type', models.CharField(choices=[('INV', 'Tax Invoice'), ('CHL', 'Delivery Challan'), ('BIL', 'Bill of Supply'), ('BOE', 'Bill of Entry'), ('CNT', 'Credit Note'), ('OTH', 'Others')], default='INV', max_length=10)),
                ('from_gstin', models.CharField(max_length=15)),
                ('from_name', models.CharField(max_length=255)),
                ('from_state_code', models.CharField(max_length=2)),
                ('from_pincode', models.CharField(blank=True, max_length=10)),
                ('to_gstin', models.CharField(blank=True, help_text='Blank when consignee is unregistered (URP).', max_length=15)),
                ('to_name', models.CharField(max_length=255)),
                ('to_state_code', models.CharField(max_length=2)),
                ('to_pincode', models.CharField(blank=True, max_length=10)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_qty_code', models.CharField(default='NOS', max_length=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transport_mode', models.CharField(choices=[('1', 'Road'), ('2', 'Rail'), ('3', 'Air'), ('4', 'Ship')], default='1', max_length=2)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('transporter_name', models.CharField(blank=True, max_length=120)),
                ('transporter_id', models.CharField(blank=True, help_text='Transporter GSTIN or 15-char Transporter ID.', max_length=15)),
                ('vehicle_no', models.CharField(blank=True, max_length=15)),
                ('transport_doc_no', models.CharField(blank=True, max_length=40)),
                ('transport_doc_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated (EWB issued)'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=12)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
                'indexes': [models.Index(fields=['status', 'invoice_date'], name='gst_returns_status_cc6951_idx'), models.Index(fields=['from_gstin', 'invoice_date'], name='gst_returns_from_gs_c00661_idx'), models.Index(fields=['eway_bill_no'], name='gst_returns_eway_bi_8a08a6_idx')],
            },
        ),
    ]
