# Generated by Django 6.0.2 on 2026-06-09 20:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_returns', '0004_gstr3b_rcm_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstr1hsnsummary',
            name='segment',
            field=models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], default='B2C', max_length=3),
        ),
        migrations.AddField(
            model_name='gstr3bsummary',
            name='outward_exempt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
