# Generated by Django 6.0.2 on 2026-05-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(blank=True, help_text='If set, only users in this AccountingRole see the notification.', max_length=30)),
                ('kind', models.CharField(choices=[('bill_overdue', 'Bill overdue'), ('emi_due', 'EMI due'), ('gstr3b_due', 'GSTR-3B filing due'), ('gstr1_due', 'GSTR-1 filing due'), ('tds_challan_due', 'TDS challan due'), ('msme_45_day', 'MSME 45-day window approaching'), ('petty_cash_low', 'Petty cash float low'), ('recurring_jv_failed', 'Recurring JV failed'), ('cheque_pending_long', 'Cheque pending > 30 days'), ('budget_overrun', 'Budget exceeded'), ('approval_required', 'Bill awaiting approval'), ('other', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('related_model', models.CharField(blank=True, help_text='e.g. "Bill", "EMISchedule" — for grouping & dedup.', max_length=100)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null = broadcast to all users with the relevant role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['kind', 'related_model', 'related_id'], name='notificatio_kind_611198_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('user', 'kind', 'related_model', 'related_id'), name='notifications_unique_open_per_target')],
            },
        ),
    ]
