# Generated by Django 6.0.2 on 2026-05-25 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_backfill_is_read_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('bill_overdue', 'Bill overdue'), ('emi_due', 'EMI due'), ('gstr3b_due', 'GSTR-3B filing due'), ('gstr1_due', 'GSTR-1 filing due'), ('tds_challan_due', 'TDS challan due'), ('msme_45_day', 'MSME 45-day window approaching'), ('petty_cash_low', 'Petty cash float low'), ('recurring_jv_failed', 'Recurring JV failed'), ('cheque_pending_long', 'Cheque pending > 30 days'), ('budget_overrun', 'Budget exceeded'), ('approval_required', 'Bill awaiting approval'), ('sync_failure', 'Sync failure (unresolved > 1h)'), ('period_lock_change', 'Period lock changed'), ('other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bill_overdue', 'Bill overdue'), ('emi_due', 'EMI due'), ('gstr3b_due', 'GSTR-3B filing due'), ('gstr1_due', 'GSTR-1 filing due'), ('tds_challan_due', 'TDS challan due'), ('msme_45_day', 'MSME 45-day window approaching'), ('petty_cash_low', 'Petty cash float low'), ('recurring_jv_failed', 'Recurring JV failed'), ('cheque_pending_long', 'Cheque pending > 30 days'), ('budget_overrun', 'Budget exceeded'), ('approval_required', 'Bill awaiting approval'), ('sync_failure', 'Sync failure (unresolved > 1h)'), ('period_lock_change', 'Period lock changed'), ('other', 'Other')], max_length=30)),
                ('muted', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'muted'], name='notificatio_user_id_ae33d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='notif_pref_uniq')],
            },
        ),
    ]
