# Generated by Django 6.0.2 on 2026-06-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct_notifications', '0003_preferences_and_alert_kinds'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='acct_notifi_user_id_bc8e57_idx',
            old_name='notificatio_user_id_427e4b_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='acct_notifi_kind_efec84_idx',
            old_name='notificatio_kind_611198_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='acct_notifi_user_id_c11334_idx',
            old_name='notificatio_user_id_ae33d1_idx',
        ),
    ]
