# Generated by Django 6.0.2 on 2026-03-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2BSalesOrderLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'b2b_sales_b2bsalesorderline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='B2BSalesOrderRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'b2b_sales_b2bsalesorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('payment_terms', models.CharField(max_length=50)),
                ('credit_days', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'customer_master_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('complete_name', models.CharField(max_length=255)),
                ('usage', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_master_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POSOrderLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pos_posorderline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POSOrderRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('sale_date', models.DateTimeField()),
                ('payment_type', models.CharField(max_length=50)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pos_posorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_code', models.CharField(blank=True, max_length=100)),
                ('pharma_hsn_code', models.CharField(blank=True, max_length=50)),
                ('pharma_gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_master_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('free_qty', models.IntegerField(default=0)),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'purchase_entry_purchaseorderline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_type', models.CharField(max_length=50)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'purchase_entry_purchaseorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturnLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'sales_return_salesreturnline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturnRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('return_type', models.CharField(max_length=10)),
                ('return_date', models.DateTimeField()),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sales_return_salesreturn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovementRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_stockmovement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_no', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('payment_terms', models.CharField(max_length=50)),
                ('credit_days', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'supplier_master_supplier',
                'managed': False,
            },
        ),
    ]
