# Generated by Django 6.0.2 on 2026-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturnLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('expiry_month', models.CharField(blank=True, max_length=7)),
                ('quantity', models.IntegerField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_return_purchasereturnline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=100)),
                ('return_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supply_type', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_return_purchasereturn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_management_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLocationAssignmentRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_management_userlocationassignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_management_userprofile',
                'managed': False,
            },
        ),
    ]
