# Generated by Django 6.0.2 on 2026-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_reader', '0002_purchasereturnlinero_purchasereturnro_rolero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollectionRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.CharField(max_length=20)),
                ('patient_id', models.PositiveIntegerField(blank=True, null=True)),
                ('doctor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'front_office_feecollection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningStockLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('expiry_month', models.CharField(blank=True, max_length=7)),
                ('quantity', models.IntegerField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_openingstockline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningStockRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_openingstock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PettyCashTxnRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('txn_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_pettycashtxn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POSPaymentRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pos_pospayment',
                'managed': False,
            },
        ),
    ]
