# Generated by Django 6.0.2 on 2026-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_reader', '0003_feecollectionro_openingstocklinero_openingstockro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchEntryRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=10)),
                ('source_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eway_bill_no', models.CharField(blank=True, max_length=50)),
                ('challan_no', models.CharField(blank=True, max_length=100)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dispatch_dispatchentry',
                'managed': False,
            },
        ),
    ]
