# Generated by Django 5.2.12 on 2026-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_reader', '0004_dispatchentryro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReversalLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('expiry_month', models.CharField(blank=True, max_length=7)),
                ('quantity', models.IntegerField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_reversal_purchasereversalline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReversalRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_no', models.CharField(blank=True, max_length=100)),
                ('reversal_type', models.CharField(max_length=10)),
                ('reversal_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supply_type', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_reversal_purchasereversal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSettingsRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.TextField()),
                ('store_phone', models.CharField(max_length=20)),
                ('store_email', models.EmailField(max_length=255)),
                ('gst_number', models.CharField(max_length=50)),
                ('drug_license', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dashboard_systemsettings',
                'managed': False,
            },
        ),
    ]
