# Generated by Django 5.2.12 on 2026-07-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_reader', '0005_purchasereversallinero_purchasereversalro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStockCorrectionLineRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.IntegerField(default=0)),
                ('old_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('old_tax_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_quantity', models.IntegerField(default=0)),
                ('new_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_tax_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'inventory_openingstockcorrectionline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningStockCorrectionRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_openingstockcorrection',
                'managed': False,
            },
        ),
    ]
