# Generated by Django 6.0.2 on 2026-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_reader', '0006_openingstockcorrectionlinero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAmendmentRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('prev_state', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_entry_purchaseamendment',
                'managed': False,
            },
        ),
    ]
