# Generated by Django 6.0.2 on 2026-05-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_accountingsettings_bill_approval_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_kind', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM (monthly), YYYY-Qx (quarterly), or YYYY (annual)', max_length=10)),
                ('cost_center', models.CharField(blank=True, help_text='Optional — restrict budget to a department / cost center.', max_length=50)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='core.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'account__account_code'],
                'constraints': [models.UniqueConstraint(fields=('period', 'account', 'cost_center', 'location_id'), name='budgets_unique_per_period_account_cc_location')],
            },
        ),
    ]
