"""
In-app notifications / alerts.

Generated by `notifications.services.generate_alerts()` (cron-driven) for
operational events: bills overdue, EMI due, GST/TDS filing approaching,
MSME 45-day window, low petty-cash float, recurring JV failed, etc.
"""
from django.contrib.auth.models import User
from django.db import models


class Notification(models.Model):
    KIND_CHOICES = [
        ('bill_overdue', 'Bill overdue'),
        ('emi_due', 'EMI due'),
        ('gstr3b_due', 'GSTR-3B filing due'),
        ('gstr1_due', 'GSTR-1 filing due'),
        ('tds_challan_due', 'TDS challan due'),
        ('msme_45_day', 'MSME 45-day window approaching'),
        ('petty_cash_low', 'Petty cash float low'),
        ('recurring_jv_failed', 'Recurring JV failed'),
        ('cheque_pending_long', 'Cheque pending > 30 days'),
        ('budget_overrun', 'Budget exceeded'),
        ('approval_required', 'Bill awaiting approval'),
        ('other', 'Other'),
    ]

    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('normal', 'Normal'),
        ('high', 'High'),
        ('critical', 'Critical'),
    ]

    user = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE,
        related_name='notifications',
        help_text='Null = broadcast to all users with the relevant role.',
    )
    role_code = models.CharField(
        max_length=30, blank=True,
        help_text='If set, only users in this AccountingRole see the notification.',
    )

    kind = models.CharField(max_length=30, choices=KIND_CHOICES, db_index=True)
    title = models.CharField(max_length=200)
    body = models.TextField(blank=True)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES,
                                default='normal')

    # Optional link target — UI navigates here when user clicks
    link_url = models.CharField(max_length=500, blank=True)
    related_model = models.CharField(max_length=100, blank=True,
        help_text='e.g. "Bill", "EMISchedule" — for grouping & dedup.')
    related_id = models.PositiveIntegerField(null=True, blank=True)

    is_read = models.BooleanField(default=False)
    read_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'is_read']),
            models.Index(fields=['kind', 'related_model', 'related_id']),
        ]
        constraints = [
            # Don't generate the same alert twice for the same target
            models.UniqueConstraint(
                fields=['user', 'kind', 'related_model', 'related_id'],
                condition=models.Q(is_read=False),
                name='notifications_unique_open_per_target',
            ),
        ]

    def __str__(self):
        return f'[{self.priority}] {self.kind}: {self.title}'
