# Generated by Django 6.0.2 on 2026-04-27 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer')], max_length=10)),
                ('party_id', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('note', 'Note')], default='email', max_length=20)),
                ('direction', models.CharField(choices=[('out', 'Outgoing'), ('in', 'Incoming')], default='out', max_length=3)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('communicated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-communicated_at', '-id'],
                'indexes': [models.Index(fields=['party_type', 'party_id'], name='parties_par_party_t_e6bb6d_idx'), models.Index(fields=['communicated_at'], name='parties_par_communi_750d8f_idx')],
            },
        ),
    ]
