# Generated by Django 6.0.2 on 2026-04-27 09:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer')], max_length=10)),
                ('party_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('as_of_date', models.DateField()),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['party_type', 'party_id'], name='parties_par_party_t_b2ebb0_idx')],
                'constraints': [models.UniqueConstraint(fields=('party_type', 'party_id'), name='parties_openingbalance_unique_party')],
            },
        ),
    ]
