# Generated by Django 6.0.2 on 2026-05-06 04:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_partyopeningbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer')], max_length=10)),
                ('party_id', models.PositiveIntegerField()),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('msme_category', models.CharField(blank=True, choices=[('', 'Not registered'), ('micro', 'Micro Enterprise'), ('small', 'Small Enterprise'), ('medium', 'Medium Enterprise')], default='', max_length=10)),
                ('msme_udyam_no', models.CharField(blank=True, help_text='UDYAM-XX-00-0000000 — MSME registration number', max_length=30)),
                ('msme_credit_period_days', models.PositiveSmallIntegerField(default=45, help_text='Per Section 15 of MSMED Act 2006: max 45 days from acceptance.')),
                ('has_lower_deduction_cert', models.BooleanField(default=False)),
                ('lower_tds_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('lower_cert_valid_from', models.DateField(blank=True, null=True)),
                ('lower_cert_valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['msme_category'], name='parties_par_msme_ca_772da0_idx'), models.Index(fields=['party_type', 'party_id'], name='parties_par_party_t_ea78d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('party_type', 'party_id'), name='parties_metadata_unique_party')],
            },
        ),
    ]
