# Generated by Django 6.0.2 on 2026-06-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_rename_journals_bi_ref_no_idx_journals_bi_ref_no_092ee9_idx_and_more'),
        ('parties', '0003_partymetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyopeningbalance',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journals.journalentry'),
        ),
    ]
