# Generated by Django 6.0.2 on 2026-06-06 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0009_alter_journalentry_reference_type"),
        ("parties", "0004_partyopeningbalance_journal_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="partyopeningbalance",
            name="parties_openingbalance_unique_party",
        ),
        migrations.AddField(
            model_name="partyopeningbalance",
            name="location_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="partyopeningbalance",
            constraint=models.UniqueConstraint(
                fields=("party_type", "party_id", "location_id"),
                name="parties_openingbalance_unique_party_loc",
            ),
        ),
    ]
