# Generated by Django 6.0.2 on 2026-03-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDSDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductee_name', models.CharField(max_length=255)),
                ('deductee_pan', models.CharField(blank=True, max_length=10)),
                ('section', models.CharField(choices=[('194C', '194C - Contractors'), ('194H', '194H - Commission/Brokerage'), ('194J', '194J - Professional/Technical Services'), ('194Q', '194Q - Purchase of Goods'), ('194I', '194I - Rent'), ('OTHER', 'Other')], max_length=10)),
                ('nature_of_payment', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deductee_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual/HUF')], default='Company', max_length=20)),
                ('source_type', models.CharField(choices=[('PurchaseOrder', 'Purchase Order'), ('Manual', 'Manual Entry')], default='Manual', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('challan_paid', 'Challan Paid'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('challan_no', models.CharField(blank=True, max_length=100)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('bsr_code', models.CharField(blank=True, max_length=20)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TDSChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=100, unique=True)),
                ('bsr_code', models.CharField(max_length=20)),
                ('deposit_date', models.DateField()),
                ('period', models.CharField(max_length=7)),
                ('section', models.CharField(max_length=10)),
                ('total_tds_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deductions', models.ManyToManyField(blank=True, related_name='challans', to='tds.tdsdeduction')),
            ],
            options={
                'ordering': ['-deposit_date'],
            },
        ),
    ]
