# Generated by Django 6.0.2 on 2026-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdsdeduction',
            name='section',
            field=models.CharField(choices=[('194C', '194C - Contractors'), ('194H', '194H - Commission/Brokerage'), ('194J', '194J - Professional/Technical Services'), ('194Q', '194Q - Purchase of Goods'), ('194I', '194I - Rent'), ('194O', '194O - E-Commerce Operator'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='TDSRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('deductee_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual/HUF')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fy_start', models.DateField()),
                ('fy_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'deductee_type'],
                'unique_together': {('section', 'deductee_type', 'fy_start')},
            },
        ),
    ]
