# Generated by Django 6.0.2 on 2026-05-06 04:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journalentry_reversal_of'),
        ('tds', '0002_alter_tdsdeduction_section_tdsrateconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCSCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_pan', models.CharField(blank=True, max_length=10)),
                ('buyer_id', models.PositiveIntegerField(blank=True, help_text='Inventory CustomerRO id, if known.', null=True)),
                ('transaction_date', models.DateField()),
                ('fy_label', models.CharField(db_index=True, help_text="e.g. '2025-26'", max_length=7)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(default='B2BSalesOrder', max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_amount', models.DecimalField(decimal_places=2, help_text='Total sale amount on the invoice (incl. GST per Circular 17/2020).', max_digits=15)),
                ('cumulative_sales_fy', models.DecimalField(decimal_places=2, help_text='Cumulative sales to this buyer in FY at time of this txn.', max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, help_text='Portion of this sale exceeding ₹50L FY-cumulative threshold.', max_digits=15)),
                ('tcs_rate', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5)),
                ('tcs_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('challan_paid', 'Challan Paid'), ('returned', 'Returned (Form 27EQ)')], default='pending', max_length=20)),
                ('challan_no', models.CharField(blank=True, max_length=100)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcs_collections', to='journals.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['fy_label', 'buyer_id'], name='tds_tcscoll_fy_labe_68e893_idx'), models.Index(fields=['status'], name='tds_tcscoll_status_926f30_idx')],
            },
        ),
    ]
