# Generated by Django 6.0.2 on 2026-05-06 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_journalentry_cost_center'),
        ('tds', '0003_tcscollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form26ASEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_label', models.CharField(db_index=True, max_length=7)),
                ('deductor_tan', models.CharField(max_length=10)),
                ('deductor_name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=10)),
                ('period', models.CharField(blank=True, max_length=7)),
                ('transaction_date', models.DateField()),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('challan_no', models.CharField(blank=True, max_length=40)),
                ('challan_bsr', models.CharField(blank=True, max_length=20)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('partial', 'Partial Match'), ('mismatch', 'Mismatch')], default='unmatched', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_26as_entries', to='journals.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['fy_label', 'deductor_tan'], name='tds_form26a_fy_labe_1a725c_idx'), models.Index(fields=['match_status'], name='tds_form26a_match_s_18a7fc_idx')],
            },
        ),
    ]
