# Generated by Django 6.0.2 on 2026-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0004_form26asentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdschallan',
            name='location_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
