# Generated by Django 6.0.2 on 2026-04-27 12:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_chartofaccount_is_active_alter_accountmapping_key'),
        ('journals', '0002_alter_journalentry_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('credit_card', 'Credit Card'), ('cash', 'Cash')], default='bank', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_account', models.ForeignKey(help_text='GL account this bank account posts to (Bank/Cash leaf)', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='core.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, help_text='Cheque #, UTR, transaction ref', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive = money in, negative = money out', max_digits=15)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Balance reported by the statement at this row', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('excluded', 'Excluded')], default='unmatched', max_length=15)),
                ('source', models.CharField(choices=[('imported', 'Imported'), ('manual', 'Manual')], default='imported', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('matched_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='journals.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['bank_account', 'status'], name='banking_ban_bank_ac_2141f3_idx'), models.Index(fields=['bank_account', 'date'], name='banking_ban_bank_ac_be3862_idx')],
                'constraints': [models.UniqueConstraint(fields=('bank_account', 'date', 'amount', 'description'), name='banking_transaction_dedupe')],
            },
        ),
    ]
