# Generated by Django 6.0.2 on 2026-05-06 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('bills', '0004_bill_bills_unique_vendor_invoice_no'),
        ('journals', '0004_journalentry_reversal_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('issued', 'Issued (we paid)'), ('received', 'Received (we collected)')], max_length=10)),
                ('cheque_date', models.DateField()),
                ('expected_clear_date', models.DateField(blank=True, help_text='Use for post-dated cheques (PDC).', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('party_type', models.CharField(blank=True, help_text='"Customer" or "Supplier"', max_length=10)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('bounce_reason', models.CharField(blank=True, max_length=255)),
                ('bounce_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Bank charge debited on bounce (if any).', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(help_text='For issued: drawer account. For received: deposit account.', on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='banking.bankaccount')),
                ('bill_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='bills.billpayment')),
                ('bounce_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounced_cheques', to='journals.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='journals.journalentry')),
            ],
            options={
                'ordering': ['-cheque_date', '-id'],
                'indexes': [models.Index(fields=['kind', 'status'], name='banking_che_kind_038e2e_idx'), models.Index(fields=['expected_clear_date'], name='banking_che_expecte_4fd62f_idx'), models.Index(fields=['party_type', 'party_id'], name='banking_che_party_t_7ad441_idx')],
                'constraints': [models.UniqueConstraint(fields=('bank_account', 'cheque_no', 'kind'), name='banking_cheque_unique_per_account')],
            },
        ),
    ]
