# Generated by Django 6.0.2 on 2026-05-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_cheque'),
        ('core', '0011_accountingsettings_bill_approval_threshold_and_more'),
        ('journals', '0005_journalentry_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField(unique=True)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('imprest_amount', models.DecimalField(decimal_places=2, help_text='The standing float to be maintained.', max_digits=12)),
                ('replenishment_threshold', models.DecimalField(decimal_places=2, help_text='Trigger replenishment when current_balance < this.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('custodian_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_account', models.ForeignKey(help_text='Cash GL — typically 1110 (Cash in Hand) or a sub-account.', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_floats', to='core.chartofaccount')),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('spend', 'Spend (debit expense)'), ('receipt', 'Receipt into float (rare)')], default='spend', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('voucher_no', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_created', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to='core.chartofaccount')),
                ('float', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banking.pettycashfloat')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_transactions', to='journals.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['float', 'date'], name='banking_pet_float_i_074700_idx')],
            },
        ),
    ]
