# Generated by Django 6.0.2 on 2026-03-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('purchase', 'Purchase Orders'), ('pos', 'POS Orders'), ('b2b', 'B2B Sales Orders'), ('return', 'Sales Returns'), ('all', 'All')], max_length=20)),
                ('last_synced_id', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-last_synced_at'],
            },
        ),
    ]
