# Generated by Django 6.0.2 on 2026-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('purchase', 'Purchase Orders'), ('pos', 'POS Orders'), ('b2b', 'B2B Sales Orders'), ('return', 'Sales Returns'), ('purchase_return', 'Purchase Returns'), ('all', 'All')], max_length=20),
        ),
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sync_type', 'resolved'], name='sync_syncer_sync_ty_3a31bd_idx')],
            },
        ),
    ]
