# Generated by Django 6.0.2 on 2026-05-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_synclog_sync_type_syncerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
