# Generated by Django 6.0.2 on 2026-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_sync_log_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('purchase', 'Purchase Orders'), ('pos', 'POS Orders'), ('b2b', 'B2B Sales Orders'), ('return', 'Sales Returns'), ('purchase_return', 'Purchase Returns'), ('b2b_amendment', 'B2B Invoice Amendments'), ('all', 'All')], max_length=20),
        ),
    ]
