# Generated by Django 6.0.2 on 2026-05-06 04:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_accountmapping_key'),
        ('journals', '0004_journalentry_reversal_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('dep_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value')], default='SLM', max_length=3)),
                ('useful_life_years', models.PositiveSmallIntegerField(help_text='Per Companies Act 2013 Sch II (e.g. Computers=3, Furniture=10)')),
                ('salvage_value_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default residual value (% of cost) — typically 5% per Sch II', max_digits=5)),
                ('wdv_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='WDV rate per IT Act §32 (e.g. Computers=40, Furniture=10).', max_digits=5)),
                ('accum_dep_account', models.ForeignKey(help_text='Accumulated Depreciation GL (contra-asset)', on_delete=django.db.models.deletion.PROTECT, related_name='asset_class_as_accum_dep', to='core.chartofaccount')),
                ('asset_account', models.ForeignKey(help_text='Asset GL (e.g. Computers — at cost)', on_delete=django.db.models.deletion.PROTECT, related_name='asset_class_as_asset', to='core.chartofaccount')),
                ('dep_expense_account', models.ForeignKey(help_text='Depreciation Expense GL (P&L)', on_delete=django.db.models.deletion.PROTECT, related_name='asset_class_as_dep_expense', to='core.chartofaccount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=120)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('useful_life_months', models.PositiveSmallIntegerField(default=0, help_text='Override of asset_class.useful_life_years × 12 if needed.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('written_off', 'Written off')], default='active', max_length=15)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gain_loss_on_disposal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquisition_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_assets', to='journals.journalentry')),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.assetclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('disposal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_assets', to='journals.journalentry')),
            ],
            options={
                'ordering': ['asset_no'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='journals.journalentry')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='fixed_assets.fixedasset')),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['status', 'asset_class'], name='fixed_asset_status_7a8385_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['location_id', 'status'], name='fixed_asset_locatio_f2ad17_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationentry',
            index=models.Index(fields=['period'], name='fixed_asset_period_be9ae7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='depreciationentry',
            unique_together={('fixed_asset', 'period')},
        ),
    ]
