# Generated by Django 6.0.2 on 2026-04-27 12:46

import django.db.models.deletion
import expenses.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_chartofaccount_is_active_alter_accountmapping_key'),
        ('journals', '0002_alter_journalentry_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('vendor_name', models.CharField(blank=True, help_text='Optional payee (free text or supplier).', max_length=255)),
                ('vendor_id', models.PositiveIntegerField(blank=True, help_text='Optional FK to inventory SupplierRO.', null=True)),
                ('reference', models.CharField(blank=True, help_text='Cheque #, invoice ref, receipt #', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recorded', 'Recorded')], default='draft', max_length=10)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='journals.journalentry')),
                ('paid_through_account', models.ForeignKey(help_text='The bank/cash/credit-card GL account that funded this expense.', on_delete=django.db.models.deletion.PROTECT, related_name='paid_through_expenses', to='core.chartofaccount')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=expenses.models._attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expense')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('account', models.ForeignKey(help_text='Expense account this line is recorded against', on_delete=django.db.models.deletion.PROTECT, related_name='expense_items', to='core.chartofaccount')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expense')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'expense_date'], name='expenses_ex_status_33d883_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_through_account'], name='expenses_ex_paid_th_b08579_idx'),
        ),
    ]
