from django.urls import path
from . import views

urlpatterns = [
    path('trial-balance/', views.TrialBalanceView.as_view(), name='trial-balance'),
    path('profit-loss/', views.ProfitLossView.as_view(), name='profit-loss'),
    path('balance-sheet/', views.BalanceSheetView.as_view(), name='balance-sheet'),
    path('ledger/', views.LedgerView.as_view(), name='ledger'),
    path('ledger/export/', views.LedgerExportView.as_view(), name='ledger-export'),
    path('receivables-aging/', views.ReceivablesAgingView.as_view(), name='receivables-aging'),
    path('open-customer-invoices/', views.OpenCustomerInvoicesView.as_view(), name='open-customer-invoices'),
    path('open-supplier-invoices/', views.OpenSupplierInvoicesView.as_view(), name='open-supplier-invoices'),
    path('payables-aging/', views.PayablesAgingView.as_view(), name='payables-aging'),
    path('bank-book/', views.BankBookView.as_view(), name='bank-book'),
    path('cash-book/', views.CashBookView.as_view(), name='cash-book'),
    path('daybook/', views.DaybookView.as_view(), name='daybook'),
    path('gst-computation/', views.GSTComputationView.as_view(), name='gst-computation'),
    path('hsn-summary/', views.HSNSummaryView.as_view(), name='hsn-summary'),
    path('party-outstanding/', views.PartyOutstandingView.as_view(), name='party-outstanding'),
    path('stock-movement/', views.StockMovementSummaryView.as_view(), name='stock-movement'),
    path('stock-valuation/', views.StockValuationView.as_view(), name='stock-valuation'),
    path('msme-compliance/', views.MSMEComplianceReportView.as_view(), name='msme-compliance'),
    path('cash-flow/', views.CashFlowStatementView.as_view(), name='cash-flow'),
    path('aged-stock/', views.AgedStockReportView.as_view(), name='aged-stock'),
    path('departmental-pl/', views.DepartmentalPLView.as_view(), name='departmental-pl'),
    path('closing-stock-recon/', views.ClosingStockReconciliationView.as_view(),
         name='closing-stock-recon'),
    path('financial-ratios/', views.FinancialRatiosView.as_view(),
         name='financial-ratios'),
    path('bank-recon-summary/', views.BankReconciliationSummaryView.as_view(),
         name='bank-recon-summary'),
]
