# Generated by Django 6.0.2 on 2026-05-06 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_accountmapping_key'),
        ('journals', '0004_journalentry_reversal_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=40, unique=True)),
                ('lender_name', models.CharField(max_length=255)),
                ('lender_id', models.PositiveIntegerField(blank=True, help_text='Optional FK to inventory SupplierRO if lender is a known vendor.', null=True)),
                ('loan_type', models.CharField(choices=[('term', 'Term Loan'), ('working_capital', 'Working Capital'), ('overdraft', 'Bank Overdraft'), ('vehicle', 'Vehicle Loan'), ('mortgage', 'Property Mortgage')], default='term', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, help_text='Annual nominal rate (%). Reducing-balance EMIs assumed.', max_digits=5)),
                ('tenure_months', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('emi_day', models.PositiveSmallIntegerField(default=5, help_text='Day of month EMI is auto-debited (1-28).')),
                ('emi_amount', models.DecimalField(decimal_places=2, help_text='Computed at create-time using PMT formula.', max_digits=15)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('written_off', 'Written off')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL)),
                ('disbursement_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_disbursements', to='journals.journalentry')),
                ('interest_expense_account', models.ForeignKey(help_text='Interest Expense GL', on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_for', to='core.chartofaccount')),
                ('liability_account', models.ForeignKey(help_text='Loan Liability GL (e.g. "HDFC Term Loan A/c")', on_delete=django.db.models.deletion.PROTECT, related_name='loan_liability_for', to='core.chartofaccount')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_principal', models.DecimalField(decimal_places=2, help_text='Outstanding principal AFTER this EMI.', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_payments', to='journals.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_schedule', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'installment_no'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'start_date'], name='loans_loan_status_1a49d9_idx'),
        ),
        migrations.AddIndex(
            model_name='emischedule',
            index=models.Index(fields=['status', 'due_date'], name='loans_emisc_status_0e3d5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emischedule',
            unique_together={('loan', 'installment_no')},
        ),
    ]
