# Generated by Django 6.0.2 on 2026-06-12 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of month EMI is auto-debited (1-28).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
