# Generated by Django 6.0.2 on 2026-03-03 04:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('voucher_type', models.CharField(choices=[('PURCHASE', 'Purchase Invoice'), ('SALE', 'Sale Invoice'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], max_length=20)),
                ('reference_type', models.CharField(blank=True, choices=[('PurchaseOrder', 'Purchase Order'), ('POSOrder', 'POS Order'), ('B2BSalesOrder', 'B2B Sales Order'), ('SalesReturn', 'Sales Return'), ('Manual', 'Manual Entry')], max_length=30)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('party_type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('None', 'None')], default='None', max_length=10)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='core.chartofaccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journals.journalentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='journals_jo_date_0deb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='journals_jo_referen_7616a3_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['voucher_type'], name='journals_jo_voucher_07c1dd_idx'),
        ),
    ]
