# Generated by Django 6.0.2 on 2026-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PurchaseOrder', 'Purchase Order'), ('POSOrder', 'POS Order'), ('B2BSalesOrder', 'B2B Sales Order'), ('SalesReturn', 'Sales Return'), ('PurchaseReturn', 'Purchase Return'), ('RCM', 'RCM Entry'), ('Manual', 'Manual Entry')], max_length=30),
        ),
    ]
