# Generated by Django 6.0.2 on 2026-04-27 13:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chartofaccount_is_active_alter_accountmapping_key'),
        ('journals', '0002_alter_journalentry_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(help_text="e.g. 'Monthly depreciation', 'Insurance prepaid'", max_length=120)),
                ('voucher_type', models.CharField(choices=[('PURCHASE', 'Purchase Invoice'), ('SALE', 'Sale Invoice'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], default='JOURNAL', max_length=20)),
                ('narration_template', models.CharField(blank=True, help_text='Tokens: {YYYY-MM}, {YYYY}, {MM}, {MON}, {DD}', max_length=500)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField()),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('auto_post', models.BooleanField(default=True, help_text='Auto-post the generated entry. Off = create as draft.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_journals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-status', 'next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('party_type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('None', 'None')], default='None', max_length=10)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_journal_lines', to='core.chartofaccount')),
                ('recurring_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journals.recurringjournal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringjournal',
            index=models.Index(fields=['status', 'next_run_date'], name='journals_re_status_b1a740_idx'),
        ),
    ]
