# Generated by Django 6.0.2 on 2026-05-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_recurringjournal_recurringjournalline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, help_text='The original posted entry that this reversal cancels (if any).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='journals.journalentry'),
        ),
    ]
