# Generated by Django 6.0.2 on 2026-05-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journalentry_reversal_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='cost_center',
            field=models.CharField(blank=True, db_index=True, help_text='Cost center / department tag, e.g. "OPD", "PHARMACY", "LAB".', max_length=50),
        ),
    ]
