# Generated by Django 6.0.2 on 2026-06-01 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_billref_voucher_profile_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billreference',
            new_name='journals_bi_ref_no_092ee9_idx',
            old_name='journals_bi_ref_no_idx',
        ),
        migrations.RenameIndex(
            model_name='billreference',
            new_name='journals_bi_bill_id_eb1571_idx',
            old_name='journals_bi_bill_id_idx',
        ),
        migrations.AlterField(
            model_name='billreference',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='billreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PurchaseOrder', 'Purchase Order'), ('POSOrder', 'POS Order'), ('B2BSalesOrder', 'B2B Sales Order'), ('SalesReturn', 'Sales Return'), ('PurchaseReturn', 'Purchase Return'), ('RCM', 'RCM Entry'), ('PartyOpeningBalance', 'Party Opening Balance'), ('Manual', 'Manual Entry')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vouchertypeprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
