# Generated by Django 6.0.2 on 2026-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_rename_journals_bi_ref_no_idx_journals_bi_ref_no_092ee9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PurchaseOrder', 'Purchase Order'), ('POSOrder', 'POS Order'), ('B2BSalesOrder', 'B2B Sales Order'), ('SalesReturn', 'Sales Return'), ('PurchaseReturn', 'Purchase Return'), ('RCM', 'RCM Entry'), ('PartyOpeningBalance', 'Party Opening Balance'), ('OpeningCarryForward', 'Opening Carry-Forward'), ('Manual', 'Manual Entry')], max_length=30),
        ),
    ]
