# Generated by Django 6.0.2 on 2026-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0008_alter_journalentry_reference_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="reference_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PurchaseOrder", "Purchase Order"),
                    ("POSOrder", "POS Order"),
                    ("B2BSalesOrder", "B2B Sales Order"),
                    ("SalesReturn", "Sales Return"),
                    ("PurchaseReturn", "Purchase Return"),
                    ("StockWriteOff", "Stock Write-off"),
                    ("StockAdjustment", "Stock Audit Adjustment"),
                    ("RCM", "RCM Entry"),
                    ("PartyOpeningBalance", "Party Opening Balance"),
                    ("OpeningCarryForward", "Opening Carry-Forward"),
                    ("Manual", "Manual Entry"),
                ],
                max_length=30,
            ),
        ),
    ]
