# Generated by Django 5.2.12 on 2026-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PurchaseOrder', 'Purchase Order'), ('POSOrder', 'POS Order'), ('B2BSalesOrder', 'B2B Sales Order'), ('SalesReturn', 'Sales Return'), ('PurchaseReturn', 'Purchase Return'), ('PurchaseReversal', 'Purchase Reversal'), ('StockWriteOff', 'Stock Write-off'), ('StockAdjustment', 'Stock Audit Adjustment'), ('RCM', 'RCM Entry'), ('PartyOpeningBalance', 'Party Opening Balance'), ('OpeningCarryForward', 'Opening Carry-Forward'), ('Manual', 'Manual Entry')], max_length=30),
        ),
    ]
