# Generated by Django 6.0.2 on 2026-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
