# Generated by Django 6.0.2 on 2026-06-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditlog_content_hash_auditlog_prev_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="location_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
