# Generated by Django 6.0.2 on 2026-03-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('tan', models.CharField(blank=True, max_length=10)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('financial_year_start', models.IntegerField(default=4)),
                ('registered_address', models.TextField(blank=True)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Accounting Settings',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('account_subtype', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Receivable', 'Receivable'), ('Payable', 'Payable'), ('Input_GST', 'Input GST'), ('Output_GST', 'Output GST'), ('TDS_Receivable', 'TDS Receivable'), ('TDS_Payable', 'TDS Payable'), ('Capital', 'Capital'), ('Retained_Earnings', 'Retained Earnings'), ('Sales', 'Sales'), ('Purchases', 'Purchases'), ('Other_Income', 'Other Income'), ('Other_Expense', 'Other Expense')], max_length=50)),
                ('is_leaf', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.chartofaccount')),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
    ]
