# Generated by Django 6.0.2 on 2026-03-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='is_fy_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='last_closed_fy',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('PURCHASES', 'Purchases'), ('INPUT_CGST', 'Input CGST'), ('INPUT_SGST', 'Input SGST'), ('INPUT_IGST', 'Input IGST'), ('TRADE_PAYABLES', 'Trade Payables'), ('SALES_POS', 'Sales - POS'), ('SALES_B2B', 'Sales - B2B'), ('OUTPUT_CGST', 'Output CGST'), ('OUTPUT_SGST', 'Output SGST'), ('OUTPUT_IGST', 'Output IGST'), ('CASH', 'Cash'), ('TRADE_RECEIVABLES', 'Trade Receivables'), ('SALES_RETURNS', 'Sales Returns'), ('PURCHASE_RETURNS', 'Purchase Returns'), ('TDS_RECEIVABLE', 'TDS Receivable'), ('TDS_PAYABLE', 'TDS Payable'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('ROUND_OFF', 'Round Off'), ('RCM_LIABILITY', 'RCM GST Liability'), ('BANK', 'Bank')], max_length=30, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='core.chartofaccount')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
