# Generated by Django 6.0.2 on 2026-04-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_account_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountmapping',
            name='key',
            field=models.CharField(choices=[('PURCHASES', 'Purchases'), ('INPUT_CGST', 'Input CGST'), ('INPUT_SGST', 'Input SGST'), ('INPUT_IGST', 'Input IGST'), ('TRADE_PAYABLES', 'Trade Payables'), ('SALES_POS', 'Sales - POS'), ('SALES_B2B', 'Sales - B2B'), ('OUTPUT_CGST', 'Output CGST'), ('OUTPUT_SGST', 'Output SGST'), ('OUTPUT_IGST', 'Output IGST'), ('CASH', 'Cash'), ('TRADE_RECEIVABLES', 'Trade Receivables'), ('SALES_RETURNS', 'Sales Returns'), ('PURCHASE_RETURNS', 'Purchase Returns'), ('TDS_RECEIVABLE', 'TDS Receivable'), ('TDS_PAYABLE', 'TDS Payable'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('ROUND_OFF', 'Round Off'), ('RCM_LIABILITY', 'RCM GST Liability'), ('BANK', 'Bank'), ('SALARY_EXPENSE', 'Salary Expense'), ('PF_PAYABLE', 'PF Payable'), ('ESI_PAYABLE', 'ESI Payable'), ('PT_PAYABLE', 'Professional Tax Payable'), ('NET_SALARY_PAYABLE', 'Net Salary Payable')], max_length=30, unique=True),
        ),
    ]
