# Generated by Django 6.0.2 on 2026-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chartofaccount_is_active_alter_accountmapping_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapping',
            name='key',
            field=models.CharField(choices=[('PURCHASES', 'Purchases'), ('INPUT_CGST', 'Input CGST'), ('INPUT_SGST', 'Input SGST'), ('INPUT_IGST', 'Input IGST'), ('TRADE_PAYABLES', 'Trade Payables'), ('SALES_POS', 'Sales - POS'), ('SALES_B2B', 'Sales - B2B'), ('OUTPUT_CGST', 'Output CGST'), ('OUTPUT_SGST', 'Output SGST'), ('OUTPUT_IGST', 'Output IGST'), ('CASH', 'Cash'), ('TRADE_RECEIVABLES', 'Trade Receivables'), ('SALES_RETURNS', 'Sales Returns'), ('PURCHASE_RETURNS', 'Purchase Returns'), ('TDS_RECEIVABLE', 'TDS Receivable'), ('TDS_PAYABLE', 'TDS Payable'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('ROUND_OFF', 'Round Off'), ('RCM_LIABILITY', 'RCM GST Liability'), ('BANK', 'Bank'), ('SALARY_EXPENSE', 'Salary Expense'), ('PF_PAYABLE', 'PF Payable'), ('ESI_PAYABLE', 'ESI Payable'), ('PT_PAYABLE', 'Professional Tax Payable'), ('NET_SALARY_PAYABLE', 'Net Salary Payable'), ('RENT_EXPENSE', 'Rent Expense'), ('ELECTRICITY_EXPENSE', 'Electricity Expense')], max_length=30, unique=True),
        ),
    ]
