# Generated by Django 6.0.2 on 2026-05-05 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_set_company_state_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('READ_ONLY', 'Read-only'), ('BOOKKEEPER', 'Bookkeeper'), ('SENIOR_ACCOUNTANT', 'Senior Accountant'), ('CFO', 'CFO'), ('AUDITOR', 'Auditor')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create_journals', models.BooleanField(default=False)),
                ('can_post_journals', models.BooleanField(default=False)),
                ('can_reverse_journals', models.BooleanField(default=False)),
                ('can_manage_masters', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_lock_period', models.BooleanField(default=False)),
                ('can_close_fy', models.BooleanField(default=False)),
                ('can_view_audit', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(blank=True, related_name='accounting_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text="YYYY-MM, e.g. '2026-04'", max_length=7, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text='Why this period was locked (e.g. "GSTR-3B filed").', max_length=255)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
    ]
