# Generated by Django 6.0.2 on 2026-05-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_accountmapping_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='bill_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bills above this amount require approval before posting. 0 = no approval required (default).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='accountmapping',
            name='key',
            field=models.CharField(choices=[('PURCHASES', 'Purchases'), ('INPUT_CGST', 'Input CGST'), ('INPUT_SGST', 'Input SGST'), ('INPUT_IGST', 'Input IGST'), ('TRADE_PAYABLES', 'Trade Payables'), ('SALES_POS', 'Sales - POS'), ('SALES_B2B', 'Sales - B2B'), ('OUTPUT_CGST', 'Output CGST'), ('OUTPUT_SGST', 'Output SGST'), ('OUTPUT_IGST', 'Output IGST'), ('CASH', 'Cash'), ('TRADE_RECEIVABLES', 'Trade Receivables'), ('SALES_RETURNS', 'Sales Returns'), ('PURCHASE_RETURNS', 'Purchase Returns'), ('TDS_RECEIVABLE', 'TDS Receivable'), ('TDS_PAYABLE', 'TDS Payable'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('ROUND_OFF', 'Round Off'), ('RCM_LIABILITY', 'RCM GST Liability'), ('BANK', 'Bank'), ('SALARY_EXPENSE', 'Salary Expense'), ('PF_PAYABLE', 'PF Payable'), ('ESI_PAYABLE', 'ESI Payable'), ('PT_PAYABLE', 'Professional Tax Payable'), ('NET_SALARY_PAYABLE', 'Net Salary Payable'), ('RENT_EXPENSE', 'Rent Expense'), ('ELECTRICITY_EXPENSE', 'Electricity Expense'), ('CLOSING_STOCK', 'Closing Stock'), ('INVENTORY_LOSS', 'Inventory Loss / Shrinkage'), ('EXPIRY_LOSS', 'Expired Stock Write-off'), ('STOCK_TRANSFER_TRANSIT', 'Stock In Transit (inter-branch)'), ('TCS_PAYABLE', 'TCS Payable'), ('BAD_DEBTS_EXPENSE', 'Bad Debts Expense (P&L)'), ('PROVISION_BAD_DEBTS', 'Provision for Doubtful Debts (contra-receivable)'), ('PETTY_CASH', 'Petty Cash')], max_length=30, unique=True),
        ),
    ]
