# Generated by Django 6.0.2 on 2026-06-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_per_location_coa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='party_id',
            field=models.PositiveIntegerField(blank=True, help_text='Inventory supplier/customer PK this ledger represents.', null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='party_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('Supplier', 'Supplier'), ('Customer', 'Customer')], default='', help_text='Set on per-party ledger leaves; blank for ordinary accounts.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['party_type', 'party_id'], name='core_charto_party_t_81fe36_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account_subtype', 'location_id'], name='core_charto_account_83d50d_idx'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('party_id__isnull', False)), fields=('party_type', 'party_id'), name='uniq_party_ledger'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.CheckConstraint(condition=models.Q(('party_id__isnull', True), ('location_id__isnull', True), _connector='OR'), name='party_ledger_shared_only'),
        ),
    ]
