# Generated by Django 6.0.2 on 2026-06-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_accountmapping_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chartofaccount",
            name="uniq_party_ledger",
        ),
        migrations.RemoveConstraint(
            model_name="chartofaccount",
            name="party_ledger_shared_only",
        ),
        migrations.AddConstraint(
            model_name="chartofaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("party_id__isnull", False)),
                fields=("party_type", "party_id", "location_id"),
                name="uniq_party_ledger_per_location",
            ),
        ),
    ]
