# Generated by Django 6.0.2 on 2026-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sales_income_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Tax Profile',
                'verbose_name_plural': 'Location Tax Profiles',
                'ordering': ['location_id'],
            },
        ),
    ]
