# Generated by Django 6.0.2 on 2026-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_locationtaxprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Admin-created shared account, visible in every store (only meaningful when location_id IS NULL).'),
        ),
    ]
